### ISSUE TITLE
Need to move docs into this project

### ISSUE THREAD

**Issue by mxz96102** [sql-machine-learning/sql-machine-learning.github.io#12]
To generate doc page under this site, need to move docs into this project,

For docs that contain "{{}}" / "{%}" like words, need to wrap in {% raw %} ... {% endraw %}

**Comment by wangkuiyi** [comment]
Thanks to @mxz96102 for the reminder!

Does it work if we add a git submodule link in this repo, pointing to the sqlflow repo, so that the whole sqlflow repo looks a subdirectory of this repo? If it works, we can keep documents of SQLFlow in the sqlflow repo, and have the doc directory in this repo as `/sqlflow/doc`.

**Comment by mxz96102** [comment]
I mean after today's merge, we also need to maintain docs in this project's 'doc' directory to generate doc site.
(BTW, docs directory is for generating site files, don's mistake it for 'doc' directory.)

**Comment by wangkuiyi** [comment]
I am still confused.  I see two directories named `doc` in this repo:

1. https://github.com/sql-machine-learning/sql-machine-learning.github.io/tree/master/docs/doc
1. https://github.com/sql-machine-learning/sql-machine-learning.github.io/tree/master/doc

Both contain some Markdown files.

Do we need them all? What is the purpose of each of them?

**Comment by mxz96102** [comment]
Now I use git submodule to maintain doc, so in next merge, there will be no doc directory, and docs directory is jekyll genreate file
